export const fillFormFields = {
  theme: {
    key: "theme",
    label: "会议主题",
    value: "0806同业需求评审",
    disabled: true,
    hidden: false,
    showType: "input",
    route: "",
    class: "mb-15",
  },
  house: {
    key: "house",
    label: "会议室",
    value: "保税区职场 303",
    disabled: true,
    hidden: false,
    showType: "route",
    route: "meetingHouse",
  },
  time: {
    key: "time",
    label: "会议时间",
    value: "7月8日 18:00-19:00",
    disabled: true,
    hidden: false,
    showType: "route",
    route: "meetingTime",
    class: "mb-15",
  },
  contractPerson: {
    key: "contractPerson",
    label: "预约人",
    value: "张宏兵",
    disabled: true,
    hidden: false,
    showType: "input",
    route: "",
  },
  phone: {
    key: "phone",
    label: "联系电话",
    value: "13866264542",
    disabled: true,
    hidden: false,
    showType: "input",
    route: "",
    class: "mb-15",
  },
  number: {
    key: "number",
    label: "会议号",
    value: "21788332",
    disabled: true,
    hidden: false,
    showType: "input",
    route: "",
  },
  takePartInPerson: {
    key: "takePartInPerson",
    label: "参会人",
    value: "艾杰、刘洋、张赫、...",
    disabled: true,
    hidden: false,
    showType: "route",
    route: "meetingTakePartInPerson",
    class: "mb-15",
  },
  introduce: {
    key: "introduce",
    label: "会议介绍",
    value: "同业需求澄清关于首...",
    disabled: true,
    hidden: false,
    showType: "route",
    route: "meetingIntroduce",
  },
  remind: {
    key: "remind",
    label: "会议提醒",
    value: "会前15分钟",
    disabled: true,
    hidden: false,
    showType: "picker",
    route: "",
    pickerVariate: "Reminds",
  },
};
export const formFields = {
  theme: {
    key: "theme",
    label: "会议主题",
    value: "",
    disabled: false,
    hidden: false,
    showType: "input",
    route: "",
    class: "mb-15",
  },
  house: {
    key: "house",
    label: "会议室",
    value: "",
    disabled: false,
    hidden: false,
    showType: "route",
    route: "meetingRoomSelect",
    class: "house-class",
  },
  time: {
    key: "time",
    label: "会议时间",
    value: "",
    disabled: true,
    hidden: true,
    showType: "route",
    route: "meetingTime",
    class: "mb-15 time-class",
  },
  contractPerson: {
    key: "contractPerson",
    label: "预约人",
    value: "张宏兵",
    disabled: true,
    hidden: true,
    showType: "input",
    route: "",
  },
  phone: {
    key: "phone",
    label: "联系电话",
    value: "13866264542",
    disabled: true,
    hidden: true,
    showType: "input",
    route: "",
    class: "mb-15",
  },
  number: {
    key: "number",
    label: "会议号",
    value: Math.floor(Math.random() * (99999999 - 1 + 1) + 1),
    disabled: true,
    hidden: true,
    showType: "input",
    route: "",
  },
  takePartInPerson: {
    key: "takePartInPerson",
    label: "参会人",
    value: "",
    disabled: false,
    hidden: false,
    showType: "route",
    route: "contactPerson",
    class: "mb-15",
  },
  introduce: {
    key: "introduce",
    label: "会议介绍",
    value: "",
    disabled: false,
    hidden: false,
    showType: "route",
    route: "meetingIntroduce",
  },
  remind: {
    key: "remind",
    label: "会议提醒",
    value: "",
    disabled: false,
    hidden: false,
    showType: "picker",
    route: "",
    pickerVariate: "Reminds",
  },
};
