export default {
  theme: {
    key: "theme",
    label: "会议主题",
    value: "会议主题会议主题",
    disabled: false,
    hidden: false,
    showType: "input",
    route: "",
    class: "mb-15",
  },
  time: {
    key: "time",
    label: "会议时间",
    value: "",
    disabled: false,
    hidden: false,
    showType: "route",
    route: "meetingTime",
  },
  house: {
    key: "house",
    label: "会议室",
    value: "",
    disabled: false,
    hidden: false,
    showType: "route",
    route: "meetingHouse",
    class: "mb-15",
  },
  contractPerson: {
    key: "contractPerson",
    label: "预约人",
    value: "张宏兵",
    disabled: true,
    hidden: true,
    showType: "input",
    route: "",
  },
  phone: {
    key: "phone",
    label: "联系电话",
    value: "13866264542",
    disabled: true,
    hidden: true,
    showType: "input",
    route: "",
    class: "mb-15",
  },
  number: {
    key: "number",
    label: "会议号",
    value: "21788332",
    disabled: true,
    hidden: true,
    showType: "input",
    route: "",
  },
  takePartInPerson: {
    key: "takePartInPerson",
    label: "参会人",
    value: "",
    disabled: false,
    hidden: false,
    showType: "route",
    route: "meetingTakePartInPerson",
    class: "mb-15",
  },
  introduce: {
    key: "introduce",
    label: "会议介绍",
    value: "",
    disabled: false,
    hidden: false,
    showType: "route",
    route: "meetingIntroduce",
  },
  remind: {
    key: "remind",
    label: "会议提醒",
    value: "",
    disabled: false,
    hidden: false,
    showType: "picker",
    route: "",
    pickerVariate: "Reminds",
  },
};
